### ISSUE TITLE
what are the files named "edgecount" and "vertexcount"?

### ISSUE THREAD

**Issue by DancyHuang** [GraphScope/gar-test#22]
what are the files named "edgecount" and "vertexcount"?  how to read them ?

**Comment by acezen** [comment]
> what are the files named "edgecount" and "vertexcount"? how to read them ?

`vertex_count` is the number of this label vertex, like https://github.com/apache/incubator-graphar-testing/blob/main/ldbc_sample/parquet/vertex/person/vertex_count is the number of person vertex, it's 8 byte int, you can read as a binary and cast to int64.
`edge_count` is the number of edge of certain chunk of vertex, like https://github.com/apache/incubator-graphar-testing/blob/main/ldbc_sample/parquet/edge/person_knows_person/ordered_by_dest/edge_count0 if the edge num of vertex chunk 0. you can cast to int64 too.

**Comment by DancyHuang** [comment]
ok， thank you.  
I 've got negative numbers previously when reading binary data using Java code。 It's ok now。
